spring:
  datasource:
    url: jdbc:sqlite:d:/test.db
    driver-class-name: org.sqlite.JDBC
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
#查询为空时 返回null
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'

server:
  port: 8088

#缓存过期时间
cacheexpire:
  captcha: 100
  account: 3600
  order: 36000

#机器位置
counter:
  id: 1000
  #网关id
  gatewayid: 1001
  #机房ID
  dataCenterId: 0
  #机柜ID
  workerId: 0

  #直连网关信息
  sendip: 127.0.0.1
  sendport: 8091
  checksum: thirdpart.checksum.ByteCheckSum
  bodycodec: thirdpart.codec.BodyCodec
  msgcodec: thirdpart.codec.MsgCodec

  pubip: 127.0.0.1
  pubport: 1883

  subbusip: 127.0.0.1
  subbusport: 1884
